### ISSUE TITLE
Distribute as binary

### ISSUE THREAD

**Issue by StefMa** [wulkano/aperture.js#19]
Hey 👋 ,

i'm very new in this topic (which node packages and stuff).
But it is possible to distribute a binary of `aperture` instead of the source code?

### The Problem
Currently we have to run it on a macOS machine (or at least on a machine which support `swift` and `xcodebuild`) because we compile the swift code at `[npm|yarn] install` time.

I'm currently experimenting with [BitBucket Pipelines](https://bitbucket.org/product/features/pipelines) which doesn't support macOS builds ATM.
Which means I can't use my app with `aperture` it :(

So it would be great if you can distribute binarys! 👍 

Thank you 👨

**Comment by sindresorhus** [comment]
Yes, that's on my todo list. PR welcome if you need it now though. Not sure why it didn't do this from the start.

**Comment by StefMa** [comment]
Cool. Would be great if we have this "feature" soon 😇

I would do that PR. But I have no idea how to do it 🙁 maybe you can send
me some links or suggestions how to do it?!

**Comment by StefMa** [comment]
I really tried to found something, but it seems that npm can't publish and distribute binarys...
-> https://github.com/npm/npm/issues/8585

So the only solution is to build it on a mac, upload it anywhere, and write a script which downloads the binary and link in the right folder 😮
Really?! 😮

**Comment by StefMa** [comment]
As mentioned in #21 the only change to make this happen is to change form `postinstall` to `prepublish`...
Currently I don't know if its working. 
But I'm working https://github.com/StefMa/aperture.js/tree/feature/binary this.

@sindresorhus the `main` swift "app" should be included now in git, right?

**Comment by StefMa** [comment]
After a quick look into the npm [publish documentation](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) maybe it is better to ignore `swift/main` in `.gitignore` but creating a empty `.npmingore`, so that `swift/main` is included in the published package but not in git ... 👍

**Comment by sindresorhus** [comment]
The best solution would be to explicitly list the files to be included with the "files" property in package.json. And still have it ignored by Git.
